apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.addonsConfig.name }}: |-
    {{ toYaml .Values.addonsConfig.config | nindent 4 }}