@startuml

title cluster module design

cloud ManagerCluster {
	component "stellaris-core" as core
	file ClusterResource as cluster

	core <-> cluster : create/listen/update
}

cloud BusinessCluster {
	component "stellaris-proxy" as proxy
	component "out-tree-addons" as addons
	file "proxy-ConfigMap" as cm

	proxy --> cm : read configuration
	proxy -> addons : http request
}

core --> proxy : deploy
proxy --> core : establish connection

@enduml∂∂