replicas: 2

image:
  registry: harmonycloud
  repository: stellaris-proxy
  tag: 0.0.1

coreAddr: example.core.addr:8080
clusterName: example-cluster

resources: {}
nodeSelector: {}
tolerations: []
pluginsConfig:
  name: plugins_config.yaml
  config:
    plugins:
      inTree:
        - name: etcd
        - name: apiserver

rbac:
  clusterRole: cluster-admin