/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "harmonycloud.cn/stellaris/pkg/apis/multicluster/v1alpha1"
	scheme "harmonycloud.cn/stellaris/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MultiClusterResourceOverridesGetter has a method to return a MultiClusterResourceOverrideInterface.
// A group's client should implement this interface.
type MultiClusterResourceOverridesGetter interface {
	MultiClusterResourceOverrides(namespace string) MultiClusterResourceOverrideInterface
}

// MultiClusterResourceOverrideInterface has methods to work with MultiClusterResourceOverride resources.
type MultiClusterResourceOverrideInterface interface {
	Create(ctx context.Context, multiClusterResourceOverride *v1alpha1.MultiClusterResourceOverride, opts v1.CreateOptions) (*v1alpha1.MultiClusterResourceOverride, error)
	Update(ctx context.Context, multiClusterResourceOverride *v1alpha1.MultiClusterResourceOverride, opts v1.UpdateOptions) (*v1alpha1.MultiClusterResourceOverride, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MultiClusterResourceOverride, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MultiClusterResourceOverrideList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceOverride, err error)
	MultiClusterResourceOverrideExpansion
}

// multiClusterResourceOverrides implements MultiClusterResourceOverrideInterface
type multiClusterResourceOverrides struct {
	client rest.Interface
	ns     string
}

// newMultiClusterResourceOverrides returns a MultiClusterResourceOverrides
func newMultiClusterResourceOverrides(c *MulticlusterV1alpha1Client, namespace string) *multiClusterResourceOverrides {
	return &multiClusterResourceOverrides{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the multiClusterResourceOverride, and returns the corresponding multiClusterResourceOverride object, and an error if there is any.
func (c *multiClusterResourceOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultiClusterResourceOverride, err error) {
	result = &v1alpha1.MultiClusterResourceOverride{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourceoverrides").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MultiClusterResourceOverrides that match those selectors.
func (c *multiClusterResourceOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultiClusterResourceOverrideList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MultiClusterResourceOverrideList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourceoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested multiClusterResourceOverrides.
func (c *multiClusterResourceOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterresourceoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a multiClusterResourceOverride and creates it.  Returns the server's representation of the multiClusterResourceOverride, and an error, if there is any.
func (c *multiClusterResourceOverrides) Create(ctx context.Context, multiClusterResourceOverride *v1alpha1.MultiClusterResourceOverride, opts v1.CreateOptions) (result *v1alpha1.MultiClusterResourceOverride, err error) {
	result = &v1alpha1.MultiClusterResourceOverride{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("multiclusterresourceoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterResourceOverride).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a multiClusterResourceOverride and updates it. Returns the server's representation of the multiClusterResourceOverride, and an error, if there is any.
func (c *multiClusterResourceOverrides) Update(ctx context.Context, multiClusterResourceOverride *v1alpha1.MultiClusterResourceOverride, opts v1.UpdateOptions) (result *v1alpha1.MultiClusterResourceOverride, err error) {
	result = &v1alpha1.MultiClusterResourceOverride{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multiclusterresourceoverrides").
		Name(multiClusterResourceOverride.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multiClusterResourceOverride).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the multiClusterResourceOverride and deletes it. Returns an error if one occurs.
func (c *multiClusterResourceOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusterresourceoverrides").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *multiClusterResourceOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusterresourceoverrides").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched multiClusterResourceOverride.
func (c *multiClusterResourceOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceOverride, err error) {
	result = &v1alpha1.MultiClusterResourceOverride{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("multiclusterresourceoverrides").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
