apiVersion: v1
kind: Namespace
metadata:
  name: stellaris-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: stellaris-agent-manager
  namespace: stellaris-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stellaris-agent-manager-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: stellaris-agent-manager
    namespace: stellaris-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stellaris-agent-manager-role
  namespace: stellaris-system
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ["get", "watch", "list", "create", "update", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stellaris-agent-manager-rolebinding
  namespace: stellaris-system
subjects:
  - kind: ServiceAccount
    name: stellaris-agent-manager
    namespace: stellaris-system
roleRef:
  kind: Role
  name: stellaris-agent-manager-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stellaris-agent-manager
  namespace: stellaris-system
  labels:
    app: stellaris-agent-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stellaris-agent-manager
  template:
    metadata:
      labels:
        app: stellaris-agent-manager
    spec:
      serviceAccountName: stellaris-agent-manager
      containers:
        - name: stellaris-agent-manager
          image: sangshen/stellairis-agent:v1.0.39
          imagePullPolicy: Always
          args:
            - --core-address=10.1.11.46:38089
            - --health-probe-addr=:9001
            - --cluster-name=cluster62