/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "harmonycloud.cn/stellaris/pkg/apis/multicluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMultiClusterResourceSchedulePolicies implements MultiClusterResourceSchedulePolicyInterface
type FakeMultiClusterResourceSchedulePolicies struct {
	Fake *FakeMulticlusterV1alpha1
	ns   string
}

var multiclusterresourceschedulepoliciesResource = schema.GroupVersionResource{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Resource: "multiclusterresourceschedulepolicies"}

var multiclusterresourceschedulepoliciesKind = schema.GroupVersionKind{Group: "multicluster.harmonycloud.cn", Version: "v1alpha1", Kind: "MultiClusterResourceSchedulePolicy"}

// Get takes name of the multiClusterResourceSchedulePolicy, and returns the corresponding multiClusterResourceSchedulePolicy object, and an error if there is any.
func (c *FakeMultiClusterResourceSchedulePolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultiClusterResourceSchedulePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(multiclusterresourceschedulepoliciesResource, c.ns, name), &v1alpha1.MultiClusterResourceSchedulePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceSchedulePolicy), err
}

// List takes label and field selectors, and returns the list of MultiClusterResourceSchedulePolicies that match those selectors.
func (c *FakeMultiClusterResourceSchedulePolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultiClusterResourceSchedulePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(multiclusterresourceschedulepoliciesResource, multiclusterresourceschedulepoliciesKind, c.ns, opts), &v1alpha1.MultiClusterResourceSchedulePolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MultiClusterResourceSchedulePolicyList{ListMeta: obj.(*v1alpha1.MultiClusterResourceSchedulePolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.MultiClusterResourceSchedulePolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested multiClusterResourceSchedulePolicies.
func (c *FakeMultiClusterResourceSchedulePolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(multiclusterresourceschedulepoliciesResource, c.ns, opts))

}

// Create takes the representation of a multiClusterResourceSchedulePolicy and creates it.  Returns the server's representation of the multiClusterResourceSchedulePolicy, and an error, if there is any.
func (c *FakeMultiClusterResourceSchedulePolicies) Create(ctx context.Context, multiClusterResourceSchedulePolicy *v1alpha1.MultiClusterResourceSchedulePolicy, opts v1.CreateOptions) (result *v1alpha1.MultiClusterResourceSchedulePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(multiclusterresourceschedulepoliciesResource, c.ns, multiClusterResourceSchedulePolicy), &v1alpha1.MultiClusterResourceSchedulePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceSchedulePolicy), err
}

// Update takes the representation of a multiClusterResourceSchedulePolicy and updates it. Returns the server's representation of the multiClusterResourceSchedulePolicy, and an error, if there is any.
func (c *FakeMultiClusterResourceSchedulePolicies) Update(ctx context.Context, multiClusterResourceSchedulePolicy *v1alpha1.MultiClusterResourceSchedulePolicy, opts v1.UpdateOptions) (result *v1alpha1.MultiClusterResourceSchedulePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(multiclusterresourceschedulepoliciesResource, c.ns, multiClusterResourceSchedulePolicy), &v1alpha1.MultiClusterResourceSchedulePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceSchedulePolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMultiClusterResourceSchedulePolicies) UpdateStatus(ctx context.Context, multiClusterResourceSchedulePolicy *v1alpha1.MultiClusterResourceSchedulePolicy, opts v1.UpdateOptions) (*v1alpha1.MultiClusterResourceSchedulePolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(multiclusterresourceschedulepoliciesResource, "status", c.ns, multiClusterResourceSchedulePolicy), &v1alpha1.MultiClusterResourceSchedulePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceSchedulePolicy), err
}

// Delete takes name of the multiClusterResourceSchedulePolicy and deletes it. Returns an error if one occurs.
func (c *FakeMultiClusterResourceSchedulePolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(multiclusterresourceschedulepoliciesResource, c.ns, name), &v1alpha1.MultiClusterResourceSchedulePolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMultiClusterResourceSchedulePolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(multiclusterresourceschedulepoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MultiClusterResourceSchedulePolicyList{})
	return err
}

// Patch applies the patch and returns the patched multiClusterResourceSchedulePolicy.
func (c *FakeMultiClusterResourceSchedulePolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultiClusterResourceSchedulePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(multiclusterresourceschedulepoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.MultiClusterResourceSchedulePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiClusterResourceSchedulePolicy), err
}
